package ajs.parkinggarageapp;

import fileserviceapp.FileService;
import fileserviceapp.GarageTotalsFormatter;
import fileserviceapp.TextFormatStrategy;
import fileserviceapp.TextReader;
import fileserviceapp.TextWriter;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 * Garage start up window. Assigns output options, fee option, file to print to
 * and garage information. Also starts the terminals.
 *
 * @author ajSchmidt-Zimmel
 * @version 1.2
 */
public class ParkingTerminalGarageOwnerStartupWindow extends javax.swing.JFrame {

    private OutputService receiptOutput;
    private OutputService salesReportOutput;
    private final String consoleO = "Console Output";
    private final String JOptionPaneO = "JOption Pane";
    private final Vector<String> outputList;
    private final String minNoMax = "Min No Max Fee";
    private final String minMax = "Min Max Fee";
    private final Vector<String> feeList;
    private FeeCalculator feeCalculator;
    private File data;
    private ParkingTerminalStartWindow start;
    private ParkingTerminal terminal;
    private CarCatalog carCatalog;

    /**
     * Creates new form ParkingTerminalGarageOwnerWindow
     */
    public ParkingTerminalGarageOwnerStartupWindow() {
        this.feeList = new Vector<>();
        this.outputList = new Vector<>();
        outputList.add(consoleO);
        outputList.add(JOptionPaneO);
        feeList.add(minMax);
        feeList.add(minNoMax);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        garageNameLabel = new javax.swing.JLabel();
        garageNameText = new javax.swing.JTextField();
        feeLabel = new javax.swing.JLabel();
        feeComboBox = new javax.swing.JComboBox(feeList);
        receiptOutputLabel = new javax.swing.JLabel();
        receiptOutputComboBox = new javax.swing.JComboBox(outputList);
        salesReportOutputLabel = new javax.swing.JLabel();
        salesReportOutputComboBox = new javax.swing.JComboBox(outputList);
        garageAddressLabel = new javax.swing.JLabel();
        garageAddressText = new javax.swing.JTextField();
        garagePhoneLabel = new javax.swing.JLabel();
        garagePhoneText = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        fileLabel1 = new javax.swing.JLabel();
        fileButton = new javax.swing.JButton();
        filePathLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Garage Owner Information Panel");

        garageNameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        garageNameLabel.setText("Garage Name:");

        garageNameText.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        feeLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        feeLabel.setText("Fee system to use: ");

        feeComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        receiptOutputLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        receiptOutputLabel.setText("Where to output receipt: ");

        receiptOutputComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        salesReportOutputLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        salesReportOutputLabel.setText("Where to output sales report: ");

        salesReportOutputComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        garageAddressLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        garageAddressLabel.setText("Garage Address");

        garageAddressText.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        garagePhoneLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        garagePhoneLabel.setText("Garage Phone Number");

        garagePhoneText.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        startButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        startButton.setText("Start Program");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        exitButton.setText("Exit Program");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        fileLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fileLabel1.setText("File to write sales to: ");

        fileButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fileButton.setText("Choose File");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        filePathLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(garageNameLabel)
                            .addComponent(feeLabel)
                            .addComponent(receiptOutputLabel)
                            .addComponent(salesReportOutputLabel)
                            .addComponent(garageAddressLabel)
                            .addComponent(garagePhoneLabel))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(garageAddressText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(garageNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(receiptOutputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(feeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salesReportOutputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(garagePhoneText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startButton)
                                .addGap(18, 18, 18)
                                .addComponent(exitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(filePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeLabel)
                    .addComponent(feeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiptOutputLabel)
                    .addComponent(receiptOutputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salesReportOutputLabel)
                    .addComponent(salesReportOutputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(garageNameLabel)
                    .addComponent(garageNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(garageAddressLabel)
                    .addComponent(garageAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(garagePhoneLabel)
                    .addComponent(garagePhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fileLabel1)
                        .addComponent(filePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (receiptOutputComboBox.getSelectedIndex() == 0) {
            try {
                receiptOutput = new OutputService(new ConsoleOutput());
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " exception in start button in receipt output creation console. garage owner screen.");
            }
        } else {
            try {
                receiptOutput = new OutputService(new JOptionPaneOutput());
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " exception in start button in receipt output creation joption pane. garage owner screen.");
            }
        }
        if (salesReportOutputComboBox.getSelectedIndex() == 0) {
            try {
                salesReportOutput = new OutputService(new ConsoleOutput());
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " exception in start button in salesReport creation console. garage owner screen.");
            }
        } else {
            try {
                salesReportOutput = new OutputService(new JOptionPaneOutput());
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " exception in start button in salesReport creation joption pane. garage owner screen.");
            }
        }

        if (feeComboBox.getSelectedIndex() == 0) {
            try {
                //minmax
                FeeCalculatorStrategy feeCalcStrat = FeeCalculatorFactory.getInstance().getFeeCalculator(FeeCalculatorFactory.FeeCalculators.MINMAX, receiptOutput);
                feeCalculator = new FeeCalculator(feeCalcStrat);
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " exception in start button in fee creation minmax. garage owner screen.");
            }
        } else {
            try {
                FeeCalculatorStrategy feeCalcStrat = FeeCalculatorFactory.getInstance().getFeeCalculator(FeeCalculatorFactory.FeeCalculators.MINNOMAX, receiptOutput);
                feeCalculator = new FeeCalculator(feeCalcStrat);
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " exception in start button in fee creation min no max. garage owner screen.");
            }
        }
        if (garageNameText.getText().isEmpty() || garageNameText.getText() == null || garageAddressText.getText().isEmpty() || garageAddressText.getText() == null || garagePhoneText.getText().isEmpty() || garagePhoneText.getText() == null || data == null) {
            ErrorWindow er = null;
            try {
                er = new ErrorWindow(this, "Fields Not Filled Out Completely");
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " error in start in error window for null argument exception. garage owner screen.");
            }
            er.setVisible(true);
            this.setVisible(false);
        } else {
            Garage garage = null;
            try {
                garage = new Garage(garageNameText.getText(), garageAddressText.getText(), garagePhoneText.getText());
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " error in initializing garage information for the garage class in start button in garage owner");
            }
            TextFormatStrategy format = new GarageTotalsFormatter();
            FileService fs = new FileService(new TextReader(format), new TextWriter(format));
            this.carCatalog = new CarCatalog();
            try {
                this.terminal = new ParkingTerminal(receiptOutput, receiptOutput, salesReportOutput, garage, feeCalculator, fs, data, carCatalog);
            } catch (IOException ex) {
                try {
                    receiptOutput.outputData(ex.toString());
                } catch (NullOrEmptyArgumentException ex1) {
                    //endless try catch problem
                    System.out.println(ex1);
                }
            } catch (NullOrEmptyArgumentException ex) {
                //endless try catch problem
                System.out.println(ex);
            }
            try {
                start = new ParkingTerminalStartWindow(this, garage, receiptOutput, terminal, salesReportOutput, feeCalculator, data, new CarCatalog());
            } catch (IOException ex) {
                try {
                    receiptOutput.outputData(ex.toString());
                } catch (NullOrEmptyArgumentException ex1) {
                    //endless try catch problem
                    System.out.println(ex1);
                }
            } catch (NullOrEmptyArgumentException ex) {
                //endless try catch problem
                System.out.println(ex);
            }
            try {
                terminal.startNewDay();
            } catch (IOException ex) {
                System.out.println(ex + " failure to start new day.");
            } catch (NullOrEmptyArgumentException ex) {
                System.out.println(ex + " failure to start new day.");
            }
            AlertWindow alert = null;
            try {
                alert = new AlertWindow(this, "New Day has been set.");
            } catch (NullOrEmptyArgumentException ex) {
                Logger.getLogger(ParkingTerminalStartWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            alert.setVisible(true);
            this.setVisible(false);
            start.setVisible(true);
            this.setVisible(false);
        }


    }//GEN-LAST:event_startButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int filePath = fileChooser.showSaveDialog(null);
        if (!(filePath == JFileChooser.APPROVE_OPTION)) {
            System.exit(0);
        }
        data = fileChooser.getSelectedFile();
        filePathLabel.setText(data.toString());
    }//GEN-LAST:event_fileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox feeComboBox;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel fileLabel1;
    private javax.swing.JLabel filePathLabel;
    private javax.swing.JLabel garageAddressLabel;
    private javax.swing.JTextField garageAddressText;
    private javax.swing.JLabel garageNameLabel;
    private javax.swing.JTextField garageNameText;
    private javax.swing.JLabel garagePhoneLabel;
    private javax.swing.JTextField garagePhoneText;
    private javax.swing.JComboBox receiptOutputComboBox;
    private javax.swing.JLabel receiptOutputLabel;
    private javax.swing.JComboBox salesReportOutputComboBox;
    private javax.swing.JLabel salesReportOutputLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
